export function purchaseError(message, code = 'PURCHASE_ERROR', statusHint = 400) {
  const err = new Error(message)
  err.code = code
  err.statusHint = statusHint
  return err
}

export const PurchaseErrorCodes = {
  INVALID_IDEMPOTENCY: 'INVALID_IDEMPOTENCY',
  PURCHASE_IN_PROGRESS: 'PURCHASE_IN_PROGRESS',
  PURCHASE_LOCKED: 'PURCHASE_LOCKED',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  PACKAGE_UNAVAILABLE: 'PACKAGE_UNAVAILABLE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_SUSPENDED: 'USER_SUSPENDED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  CHECKOUT_EXPIRED: 'CHECKOUT_EXPIRED',
  CHECKOUT_NOT_FOUND: 'CHECKOUT_NOT_FOUND',
  CHECKOUT_MISMATCH: 'CHECKOUT_MISMATCH',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
}
